# Generated by Django 2.0.6 on 2018-06-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cusapp',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
